#!/bin/ansible-playbook
#
# Title:      plex-docker
# Author(s):  Admin9705
# Moded:      MrDoob for ptS-Comm
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'plex'
        intport: '32400/tcp'
        extport: '32400'
        intport2: '3005/tcp'
        extport2: '3005'
        intport3: '8324/tcp'
        extport3: '8324'
        intport4: '32410/udp'
        extport4: '32410'
        intport5: '32412/udp'
        extport5: '32412'
        intport6: '32413/udp'
        extport6: '32413'
        intport7: '32414/udp'
        extport7: '32414'
        image: 'plexinc/pms-docker:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: 'Including Tasks'
      include_tasks: '/opt/coreapps/apps/templates/tasks/dynamic.yml'

    # FACTS #######################################################################
    - name: 'Plex Server Network Type'
      shell: 'cat /var/plexguide/plex.server'
      register: servertype

    - name: Register Claim Number
      shell: 'cat /var/plexguide/plex.claim'
      register: claim
      when: servertype.stdout == "remote"

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    ######################################### FOR BOTH
    - name: 'Set Default Labels'
      set_fact:
        default_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Set Default Volume - {{ extension.stdout }}'
      set_fact:
        default_volumes:
          - '{{path.stdout}}:{{path.stdout}}'
          - '/mnt:/mnt'
          - '/opt/appdata/{{pgrole}}/database:/config'
          - '/tmp:/tmp'
          - '/opt/transcodes:/transcode'
          - '/dev/shm:/ram_transcode'

    - name: 'Establish Key Variables'
      set_fact:
        default_env:
          UID: '1000'
          GID: '1000'
          #  linuxserver.io enable linuxserver.io compatability. #
          PUID: '1000'
          PGID: '1000'

    - name: Check Preferences.xml exists
      stat:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Preferences.xml'
      register: plex_prefs

    ############### This is needed because on a fresh installaions the value is missing and is defaulted to 1 Security perfered
    - name: secureConnections is missing
      xml:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Preferences.xml'
        xpath: /Preferences/@secureConnections
        count: yes
      register: secure_hits
      when:
        - plex_prefs.stat.exists

      ############### This is needed because on a fresh installaions the value is missing and is defaulted to 1 Security perfered
    - name: Add secureConnections if missing
      xml:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Preferences.xml'
        xpath: /Preferences
        attribute: secureConnections
        value: '1'
      when:
        - plex_prefs.stat.exists
        - secure_hits.count == 0

    - name: Read Preferences.xml
      xml:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Preferences.xml'
        xpath: /Preferences
        content: attribute
      register: plex_pref_content
      when: plex_prefs.stat.exists

    - name: Add https to default_label if secureConnection != 2
      set_fact:
        default_labels: "{{default_labels | combine( {'traefik.protocol': 'https'} )}}"
      when:
        - plex_prefs.stat.exists
        - plex_pref_content.matches[0]['Preferences']['secureConnections']

    - name: Read customConnections
      set_fact:
        customConnections: "{{plex_pref_content.matches[0]['Preferences']['customConnections']}}"
      when:
        - plex_prefs.stat.exists
        - plex_pref_content.matches[0]['Preferences']['customConnections'] is defined

    - name: customConnections missing
      set_fact:
        customConnections: 'http://{{ipaddress.stdout}}:32400, http://plex.{{domain.stdout}}:32400'
      when:
        - plex_prefs.stat.exists == False

    - name: 'Get Plex Custom URL'
      shell: 'echo https://plex.{{domain.stdout}}:443,http://plex.{{domain.stdout}}:80'
      register: plex_url
      when: servertype.stdout == "remote"

    - debug: msg="Your plex_url is {{ plex_url.stdout }}"
      when: servertype.stdout == "remote"

    - set_fact:
        plex_advert_ip: 'http://{{ipaddress.stdout}}:32400'
      when: servertype.stdout == "remote"

    - set_fact:
        plex_advert_ip: '{{plex_url.stdout}}'
      when: servertype.stdout == "remote"

    - debug: msg="plex_advert_ip is {{plex_advert_ip}}"
      when: servertype.stdout == "remote"

    ########################################## Other
    - name: Check /dev/dri exists
      stat:
        path: '/dev/dri'
      register: dev_dri

    - name: Create Transcodes Directory
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /opt/transcodes

    - name: customConnections FailSafe
      set_fact:
        customConnections: 'none'
      when: customConnections is undefined

    ######################################### DEPLOY PLEX REMOTE (ANSWER 2)
    - name: Deploy Plex Container (Remote Edition)
      docker_container:
        name: plex
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
          - '{{ports.stdout}}{{extport3}}:{{intport3}}'
          - '{{ports.stdout}}{{extport4}}:{{intport4}}'
          - '{{ports.stdout}}{{extport5}}:{{intport5}}'
          - '{{ports.stdout}}{{extport6}}:{{intport6}}'
          - '{{ports.stdout}}{{extport7}}:{{intport7}}'
        env:
          PLEX_UID: '1000'
          PLEX_GID: '1000'
          PLEX_CLAIM: '{{claim.stdout}}'
          ADVERTISE_IP: '{{customConnections}}'
        purge_networks: yes
        networks:
          - name: plexguide
            aliases:
              - plex
        volumes: '{{default_volumes}}'
        devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
        etc_hosts:
          { 'analytics.plex.tv': '127.0.0.1', 'metrics.plex.tv': '127.0.0.1' }
        restart_policy: unless-stopped
        state: started
        labels: '{{default_labels}}'
      when: servertype.stdout == "remote"

    ######################################### DEPLOY PLEX LOCAL (ANSWER 3)
    - name: Deploy Plex Container (Local Edition)
      docker_container:
        name: plex
        image: '{{image}}'
        pull: yes
        published_ports:
          - '32400:32400/tcp'
          - '3005:3005/tcp'
          - '8324:8324/tcp'
          - '32469:32469/tcp'
          - '1900:1900/udp'
          - '32410:32410/udp'
          - '32412:32412/udp'
          - '32413:32413/udp'
          - '32414:32414/udp'
        env:
          PLEX_UID: '1000'
          PLEX_GID: '1000'
          ADVERTISE_IP: '{{customConnections}}'
        networks:
          - name: plexguide
            aliases:
              - plex
        volumes: '{{default_volumes}}'
        devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
        etc_hosts:
          { 'analytics.plex.tv': '127.0.0.1', 'metrics.plex.tv': '127.0.0.1' }
        restart_policy: unless-stopped
        state: started
        labels: '{{default_labels}}'
      when: servertype.stdout == "local"

    # PLUGINS ####################################################
      #/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins
     ####Radarr Bundle
    - name: Check Radarr.Bundle exist
      stat:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/Radarr.bundle'
      register: stat_result_radarr

    - name: Clone Radarr.Bundle
      git:
        repo: 'https://github.com/piplongrun/Radarr.bundle.git'
        dest: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/Radarr.bundle'
        force: yes
      when:
        - stat_result_radarr.stat.exists == False

     ####Sonarr Bundle
    - name: Check Sonarr.Bundle exist
      stat:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/Sonarr.bundle'
      register: stat_result_sonarr

    - name: Clone Sonarr.Bundle
      git:
        repo: 'https://github.com/piplongrun/Sonarr.bundle.git'
        dest: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/Sonarr.bundle'
        force: yes
      when:
        - stat_result_sonarr.stat.exists == False

     ####OpenMovieDatabase Bundle
    - name: Check OpenMovieDatabase.Bundle exist
      stat:
        path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/OpenMovieDatabase.bundle'
      register: stat_result_openmovie

    - name: Clone OpenMovieDatabase.Bundle
      git:
        repo: 'https://github.com/piplongrun/OpenMovieDatabase.bundle.git'
        dest: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/OpenMovieDatabase.bundle'
        force: yes
      when:
        - stat_result_openmovie.stat.exists == False    
        ########EOF BUNDLE
        #####Db edits 
    - name: "Install package for Plex-DB Cache size Fix"
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - sqlite3
        
    - name: "Install package for Plex-DB Cache size Fix"
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - sqlite3

    - name: Get Current Plex DB Cache Size
      shell: |
        sqlite3 "/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db" \
        "PRAGMA default_cache_size;"
      args:
        executable: /bin/bash
      register: current_db_cache_size

    - name: Set 'default_db_cache_size' variable
      set_fact:
        default_db_cache_size: '2000'

    - name: Check if 'plex.db_cache_size' was specified
      set_fact:
        db_cache_size_is_specified: "{{ true if not (
            (plex.db_cache_size is undefined)
            or
            (plex.db_cache_size is none)
            or
            (plex.db_cache_size | trim | length == 0)
          )
          else false }}"

    - name: Get Desired Plex DB Cache Size
      set_fact:
        desired_db_cache_size: "{{ default_db_cache_size
          if ( (not db_cache_size_is_specified) or (plex.db_cache_size == 'default') )
          else ( (plex.db_cache_size) | regex_replace(',', '') | int ) }}"

    - name: Make Plex DB Edits
      block:

      - name: Stop Plex Container
        docker_container:
          name: plex
          state: stopped
        when: ('plex_db_cache_size' in ansible_run_tags)

      - name: Display Desired Plex DB Cache Size
        debug:
          msg: "Desired Plex DB Cache Size is '{{ desired_db_cache_size }}'"

      - name: "Set Plex DB Cache Size"
        shell: |
          sqlite3 "/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db" \
            "PRAGMA default_cache_size = '{{ desired_db_cache_size | int }}';"
        args:
          executable: /bin/bash

      - name: Get New Plex DB Cache Size
        shell: |
          sqlite3 "/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db" \
            "PRAGMA default_cache_size;"
        args:
          executable: /bin/bash
        register: new_db_cache_size

      - name: Display New Plex DB Cache Size
        debug:
          msg: "Plex DB cache size is now set to '{{ new_db_cache_size.stdout | int }}'."
       #####EOF.DB.EDITS

      - name: Start Plex Container
        docker_container:
          name: plex
          state: started
        when: ('plex_db_cache_size' in ansible_run_tags)
      #### EOF Bundle ADD

    - debug: msg="Final Notes - Remote Plex | IP Address {{ipaddress.stdout}} | Plex Type {{servertype.stdout}} | Token {{claim.stdout}}"
      when: servertype.stdout == "remote"

    - debug: msg="Final Notes - Local Plex | IP Address {{ipaddress.stdout}} | Plex Type {{servertype.stdout}}"
      when: servertype.stdout == "local"
