#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'tautulli'
        intport: '8181'
        extport: '8181'
        image: 'linuxserver/tautulli'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'
    - name: 'Including plugins '
      include_tasks: '/opt/coreapps/apps/_plugins.yml'
    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/{{pgrole}}/config.ini
      register: confcheck
    - name: 'Including Tasks'
      include_tasks: '/opt/coreapps/apps/templates/tasks/dynamic.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          #traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/config'
          - '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Logs:/logs'
          - '/opt/appdata/{{pgrole}}/scripts:/scripts'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: '${TZ}' 
    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # Undeployed ########################################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: 'Waiting for {{pgrole}} to start'
          wait_for:
            path: '/opt/appdata/{{pgrole}}/config.ini'
            state: present
        - name: 'Stop Container'
          docker_container:
            name: '{{pgrole}}'
            state: stopped
        - name: 'Restart {{pgrole}}'
          docker_container:
            name: '{{pgrole}}'
            state: started
        - name: 'update {{pgrole}}'
          shell: 'sudo docker exec -it tautulli apt-get update -yqq'
        - name: 'pip update for {{pgrole}}'
          shell: 'sudo docker exec -it tautulli pip install --upgrade PIP'
        - name: 'pip install jsonrpclib-pelix for tautulli'
          shell: 'sudo docker exec -it {{pgrole}} pip install jsonrpclib-pelix'
      when: not confcheck.stat.exists

    # deployed ########################################################################
    - name: 'Update {{pgrole}}'
      block:
        - name: 'Waiting for {{pgrole}} to start'
          wait_for:
            path: '/opt/appdata/{{pgrole}}/config.ini'
            state: present
        - name: 'Stop Container'
          docker_container:
            name: '{{pgrole}}'
            state: stopped
        - name: 'Restart {{pgrole}}'
          docker_container:
            name: '{{pgrole}}'
            state: started
        - name: update docker {{pgrole}}
          shell: 'sudo docker exec -it {{pgrole}} apt-get update -yqq'
        - name: pip update for {{pgrole}}´
          shell: 'sudo docker exec -it tautulli pip install --upgrade PIP'
        - name: pip install jsonrpclib-pelix for {{pgrole}}
          shell: 'sudo docker exec -it {{pgrole}} pip install jsonrpclib-pelix'
      when: confcheck.stat.exists
